### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/normtestPY#18]
good Job! The project proposal is very beautiful, but some problem presents on test cases:

- For test_make_qqplot(), you should also consider testing the input. Is the input is the correct type? Is the input meaningful? Think about some extreme cases.

- For the test of shapiro_wilk(), the meanless input should also be considered.

- 2-3 grammar errors presents, please check before submitting. You can use some online grammar checker.

**Comment by LeeYinYing** [comment]
Thank you Doris, we have addressed your feedbacks in our new issues for Milestone 2 and Milestone 3. Please see these issues for references
#22 - Update Readme
#23 - Test cases needed
