### ISSUE TITLE
Test cases needed

### ISSUE THREAD

**Issue by LeeYinYing** [UBC-MDS/normtestPY#23]
`make_qqplot`:
- [x] test for correct input types. Address extreme cases

`shapiro_wilk`:
- [x] test for meaningless inputs

`params_mle`:
- [ ] Consider infinite numbers exceptions

**Comment by shusterc** [comment]
shapiro_wilk test for meaningless inputs added

**Comment by LeeYinYing** [comment]
Need 100% branch coverage for each function
Place checkmark for the function when its done.

* [ ]  `make_qqplot` (Richie)
* [ ]  `shapiro_wilk` (Coste)
* [ ]  `params_mle` (Sylvia)

**Comment by shusterc** [comment]
Improved test coverage to 86%
- most other coverage is in handling datatypes, will need to work on this further
- some loops won't count for some reason
- not sure if we need code for W >=1
