### ISSUE TITLE
Feedback of Milestone 2

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/normtestPY#40]
- Eight tests failed in test_make_qqplot.py.
- Your package can successfully install but have the problem to run the function when I call "from normtestPY.normtestPY.params_mle import params_mle"

**Comment by rzitomer** [comment]
Thanks for the feedback. I am not able to reproduce these issues locally and was hoping you could shed more light on how you encountered them. Below are the steps I took to try to reproduce these issues as well as my best guess for what could have gone wrong. Thanks!

For test_make_qqplot.py: I deleted our repo locally and then re-cloned it and am successfully able to run all tests by running `pytest` while in the directory: <img width="721" alt="screen shot 2019-02-20 at 12 48 57 pm" src="https://user-images.githubusercontent.com/7307932/53290938-1cbc4780-3760-11e9-8db5-ce5542067cf1.png"> 
I also downloaded the zip file of our milestone 2 release, unzipped it, and ran `pytest` from within that directory and am also successfully able to run all tests. The only thing I can think of that could potentially lead to an issue is that I do have to go through and manually close all of the plots that pop up as the tests are run.

For importing params_mle: I first pip uninstalled our package locally, deleted my local copy of the package, etc. Then I re-pip installed our package. After the package installed I stepped into an interactive python session and was able to load and use all three functions (including params_mle). I loaded each function by doing
`from normtestPY.params_mle import params_mle` not `from normtestPy.normtestPY.params_mle import params_mle` as you mentioned so maybe that could be the issue? I'm not sure whether or not you used pip to install the package, which might be why I can't recreate the issue.

Let me know if you need any more info. Thanks for your help.

**Comment by Doooooris** [comment]
Sorry, I rechecked the problem, and I notice the test failed problem is caused by numpy. quantile(). This function is only contained in Numpy 1.15.0. My numpy is 1.13, so that's why the test failed. Anyway, now it passed. 
However, your package usage is wrong, 
"from normtestPY.normtestPY.params_mle import params_mle
from normtestPY.normtestPY.shapiro_wilk import shapiro_wilk
from normtestPY.normtestPY.make_qqplot import make_qqplot"
You should change it to "from normtestPY.params_mle import params_mle".

**Comment by rzitomer** [comment]
Thanks for the response, makes sense. We'll change setup.py to require at least numpy 1.15.0 and change the usage to say `from normtestPY.params_mle import params_mle` instead of `from normtestPY.normtestPY.params_mle import params_mle`

**Comment by rzitomer** [comment]
Okay we've made the discussed changes (required numpy 1.15.0 and updated usage).
